import { ProductType } from "@/app/definitions";

export const ALL_PRODUCTS: ProductType[] = [
    {
        id: "1sdf",
        model: "Nike Air Force 1 '07 EasyOn",
        brand: "Nike",
        cost: 99,
        category: "men",
        description: "Quicker than 1, 2, 3—the original hoops shoe lets you step in and get going. Its EasyOn entry system gives you a hands-free experience, while crisp leather dons the cleanest color for ultimate wearability. Yeah, it's everything you love and then some.",
        sizes: [8, 9, 10, 11, 12, 13],
    },
    {
        id: "22134dfq",
        model: "Nike Roshrun",
        brand: "Nike",
        cost: 50,
        category: "men",
        description: "Effortless as a breeze—the Nike RosheRun offers a seamless entry and instant comfort. Its EasyOn design ensures a hands-free experience, while the sleek mesh upper provides breathability and style. With its lightweight construction and versatile appeal, it's everything you love and more.",
        sizes: [8, 9, 10, 11, 12, 13],
    },
    {
        id: "3adfq",
        model: "Adidas Ultraboost",
        brand: "Adidas",
        cost: 150,
        category: "men",
        description: "The Adidas Ultraboost is designed for a responsive and supportive feel. Its comfortable knit upper and energy-returning midsole deliver a snug fit with every step.",
        sizes: [7, 8, 9, 10, 11],
    },
    {
        id: "4dfqwe",
        model: "Jordan Retro 4",
        brand: "Jordan",
        cost: 200,
        category: "men",
        description: "The Jordan Retro 4 combines iconic style with modern comfort. Featuring premium materials and Air-Sole cushioning, this shoe delivers all-day comfort and support.",
        sizes: [8, 9, 10, 11, 12],
    },
    {
        id: "5asdfqwer",
        model: "Nike Air Max 270",
        brand: "Nike",
        cost: 150,
        category: "women",
        description: "The Nike Air Max 270 is inspired by two icons of big Air: the Air Max 180 and Air Max 93. It features Nike's biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks.",
        sizes: [6, 7, 8, 9, 10],
    },
    {
        id: "6svg",
        model: "Adidas NMD R1",
        brand: "Adidas",
        cost: 130,
        category: "women",
        description: "The Adidas NMD R1 offers a sleek look with responsive cushioning. Its knit upper provides lightweight support, while Boost cushioning delivers maximum comfort with every step.",
        sizes: [5, 6, 7, 8],
    },
    {
        id: "7234dsa",
        model: "Puma Cali",
        brand: "Puma",
        cost: 80,
        category: "women",
        description: "The Puma Cali takes inspiration from the West Coast and blends it with Puma's classic heritage. Its clean design and comfortable construction make it a versatile option for everyday wear.",
        sizes: [6, 7, 8, 9],
    },
    {
        id: "7cccsrt",
        model: "New Balance 574",
        brand: "New Balance",
        cost: 90,
        category: "men",
        description: "The New Balance 574 combines retro style with modern comfort. Featuring a durable suede and mesh upper and ENCAP midsole cushioning, this shoe offers all-day support.",
        sizes: [7, 8, 9, 10, 11],
    },
    {
        id: "8sdfwrt",
        model: "Reebok Classic Leather",
        brand: "Reebok",
        cost: 80,
        category: "men",
        description: "The Reebok Classic Leather is an iconic sneaker known for its timeless style and comfortable fit. With a soft leather upper and EVA midsole, this shoe delivers lightweight cushioning.",
        sizes: [8, 9, 10, 11, 12],
    },
    {
        id: "8dfthyh",
        model: "Vans Old Skool",
        brand: "Vans",
        cost: 60,
        category: "men",
        description: "The Vans Old Skool is a classic skate shoe known for its durability and style. Featuring a canvas and suede upper and padded collar for support and flexibility.",
        sizes: [7, 8, 9, 10, 11],
    },
    {
        id: "9sdfaqq",
        model: "Converse Chuck Taylor All Star",
        brand: "Converse",
        cost: 55,
        category: "men",
        description: "The Converse Chuck Taylor All Star is a timeless classic with a canvas upper and iconic silhouette. Its durable rubber outsole provides traction and support for all-day wear.",
        sizes: [8, 9, 10, 11, 12],
    },
    {
        id: "1sdfq0",
        model: "Skechers D'Lites",
        brand: "Skechers",
        cost: 70,
        category: "women",
        description: "The Skechers D'Lites is a stylish and comfortable sneaker featuring a chunky design and Air-Cooled Memory Foam insole for all-day comfort. Its lace-up front allows for a secure fit.",
        sizes: [6, 7, 8, 9],
    },
    {
        id: "1saft1",
        model: "Under Armour Charged Assert 8",
        brand: "Under Armour",
        cost: 70,
        category: "women",
        description: "The Under Armour Charged Assert 8 is a lightweight and breathable running shoe designed for comfort and support. Featuring a lightweight mesh upper and Charged Cushioning midsole for responsive cushioning.",
        sizes: [5, 6, 7, 8],
    },
    {
        id: "1asdfqr2",
        model: "Asics GEL-Excite 8",
        brand: "Asics",
        cost: 75,
        category: "women",
        description: "The Asics GEL-Excite 8 is a versatile running shoe with a breathable mesh upper and Rearfoot GEL Cushioning System for shock absorption. Its AmpliFoam midsole provides cushioning and flexibility.",
        sizes: [6, 7, 8, 9],
    },
    {
        id: "13sadft",
        model: "Brooks Ghost 14",
        brand: "Brooks",
        cost: 130,
        category: "women",
        description: "The Brooks Ghost 14 is a neutral running shoe designed for comfort and versatility. Featuring DNA Loft cushioning and a Segmented Crash Pad, this shoe provides a smooth and responsive ride.",
        sizes: [6, 7, 8, 9],
    },
];
