import { ArticleDataType } from "@/app/definitions";

export const ARTICLES_DATA: ArticleDataType[] = [
  {
    title: "About us",
    id: "about-us",
    fullText: "In the vibrant tapestry of online fashion, Nysc Shoes emerged as a beacon of style and compassion in the year 2020. What began as a dream soon transformed into a reality, as the founders envisioned a space where footwear wasn't just a necessity but a statement of individuality and global responsibility. && Founded in the midst of a challenging year, Nysc Shoes stood resilient, determined to bring a positive impact to the world. In just a short span, the store became a favorite among fashion enthusiasts, growing to boast a community of over a million satisfied customers. && The founders of Nysc Shoes, driven by a passion for fashion and a desire to make a difference, set out to redefine the online shopping experience. With a keen eye for trends and an unwavering commitment to quality, they curated a collection that resonated with the diverse tastes of their growing clientele. && Beyond fashion, the heart of Nysc Shoes beats with a spirit of philanthropy. Embracing the principle of giving back, the store actively engages in charitable initiatives aimed at making a positive impact on the community and the world at large. From local outreach programs to global partnerships, Nysc Shoes believes in using its success to contribute to a brighter and more compassionate future. && The success of Nysc Shoes isn't just measured in numbers; it's reflected in the stories of customers who found the perfect pair, in the joy of giving, and in the positive ripples created by a community united by a love for fashion and a shared vision for a better world. && As the brand continues to flourish, it remains committed to its founding principles – offering top-notch footwear, fostering a sense of style and individuality, and making a meaningful difference in the world. Nysc Shoes isn't just a store; it's a movement, a celebration of fashion with a purpose, and a testament to the transformative power of a community that cares. && Step into the world of Nysc Shoes, where every purchase is a step towards self-expression, compassion, and a brighter, more stylish tomorrow."
  },
  {
    title: "How to choose the best running shoes?",
    id: "how-to-choose-the-best-running-shoes",
    fullText: "Embarking on a running journey is an exhilarating experience, and the right pair of running shoes can make all the difference. Whether you're a seasoned marathoner or a novice hitting the pavement for the first time, selecting the ideal running shoes is crucial for comfort, performance, and injury prevention. && Here's your comprehensive guide to finding the perfect running shoes: && 1. Understand Your Foot Type: Begin by identifying your foot type. Are you an overpronator, underpronator, or do you have a neutral gait? Knowing this helps determine the level of support and cushioning your feet require. && 2. Get to Know Your Arch: Your arch type influences the distribution of impact forces while running. High, normal, or low arches each have specific shoe requirements. Understanding your arch helps in selecting shoes with the right arch support. && 3. Assess Your Running Terrain: Consider the surface you'll be running on – be it trails, roads, or a mix of both. Different terrains demand different features in running shoes. Trail shoes offer more traction, while road shoes focus on lightweight construction. && 4. Know Your Running Style: Your running style and goals influence the type of shoes you need. If you're a sprinter, you might prefer lightweight and responsive shoes. Long-distance runners may prioritize cushioning and durability. && 5. Measure Your Feet Regularly: Believe it or not, your shoe size can change over time. Measure your feet regularly to ensure a proper fit. Feet tend to swell during a run, so consider shopping for shoes in the late afternoon or evening. && 6. Comfort is Key: Always prioritize comfort. Your running shoes should feel snug but not tight. Make sure there's enough room in the toe box to prevent black toenails and blisters. Walk around and jog a bit in the store to assess the comfort level. && 7. Test the Flexibility: A good pair of running shoes should bend at the ball of the foot but remain sturdy in the arch. This balance ensures proper support and flexibility, contributing to a more natural stride. && 8. Consider the Right Cushioning: The level of cushioning depends on your personal preference and the distance you plan to cover. Some runners prefer a plush feel for longer distances, while others may opt for a firmer cushioning for speed. && 9. Allow Room for Orthotics: If you use orthotic insoles, ensure the running shoes have enough space to accommodate them comfortably. Some shoes come with removable insoles, providing flexibility for custom orthotics. && 10. Seek Professional Advice: Don't hesitate to seek advice from professionals at specialty running stores. They can analyze your gait, foot type, and running style to recommend the most suitable options. Remember, investing time and effort into choosing the right running shoes pays off in the long run – both in terms of comfort and injury prevention. Lace up, hit the pavement, and enjoy every stride on your running journey."
  },
  {
    title: "The Evolution of Sneaker Culture",
    id: "the-evolution-of-sneaker-culture",
    fullText: "Sneakers have transcended their humble beginnings as athletic footwear to become iconic symbols of style, self-expression, and cultural identity. From the basketball courts to the catwalks, sneakers have left an indelible mark on fashion and society, evolving into a billion-dollar industry with a rich and diverse history. && The early 20th century saw the emergence of the first rubber-soled sneakers, designed to provide comfort and support for athletes on the go. Brands like Converse and Keds pioneered the canvas sneaker, offering affordable and versatile footwear for the masses. && The post-war era witnessed the rise of basketball sneakers as stars like Chuck Taylor and Kareem Abdul-Jabbar popularized brands like Converse and Adidas on the court. Sneakers became synonymous with athleticism and urban culture, transcending their utilitarian roots to become fashion statements in their own right. && The 1980s marked a turning point in sneaker culture with the introduction of Air Jordans by Nike. Endorsed by basketball legend Michael Jordan, Air Jordans revolutionized the sneaker industry, combining cutting-edge technology with bold design and celebrity endorsement. Sneakers became status symbols, coveted by collectors and enthusiasts alike. && The 1990s saw the emergence of sneakerhead culture, fueled by hip-hop and streetwear fashion. Sneaker enthusiasts, or sneakerheads, collected rare and limited-edition kicks, trading, selling, and showcasing their prized possessions as a form of self-expression and cultural currency. && In the 21st century, sneaker culture has gone global, with brands collaborating with artists, designers, and celebrities to create limited-edition releases and exclusive collections. Sneakers have become collector's items, with resale markets booming and prices skyrocketing for rare and coveted pairs. && Today, sneaker culture continues to thrive as a vibrant and dynamic subculture, embracing diversity, creativity, and individuality. From high-tops to low-tops, from retro classics to futuristic designs, sneakers remain at the forefront of fashion, reflecting the ever-changing tastes and trends of society. && The evolution of sneaker culture is a testament to the enduring appeal of these iconic shoes – not just as footwear, but as symbols of style, status, and cultural identity. As sneakers continue to evolve and innovate, one thing remains certain: the love affair between sneakerheads and their kicks shows no signs of slowing down."
  },
  {
    title: "How to care for your sneakers?",
    id: "how-to-care-for-your-sneakers",
    fullText: "Caring for your sneakers not only prolongs their lifespan but also keeps them looking fresh and stylish. Follow these simple steps to ensure your sneakers stay in top condition: && 1. Clean Regularly: Remove dirt and stains promptly to prevent them from setting in. Use a soft-bristled brush or cloth dipped in a mild cleaning solution to gently scrub the surface of your sneakers. For stubborn stains, consider using a specialized sneaker cleaner. && 2. Air Dry: After cleaning, allow your sneakers to air dry naturally. Avoid using direct heat sources such as hairdryers or radiators, as excessive heat can damage the materials and cause them to lose their shape. Stuff your sneakers with crumpled paper towels to help them retain their shape as they dry. && 3. Protect with Waterproof Spray: Apply a waterproof spray to protect your sneakers from water damage and stains. Be sure to choose a spray specifically formulated for the materials of your sneakers, whether they're leather, suede, or fabric. Follow the manufacturer's instructions for best results. && 4. Store Properly: When not in use, store your sneakers in a cool, dry place away from direct sunlight. Avoid overcrowding them in a tight space, as this can cause them to lose their shape or develop creases. Consider using a shoe rack or storage box to keep them organized and protected. && 5. Rotate Your Sneakers: Rotate between multiple pairs of sneakers to allow each pair to air out and regain their shape between wears. This also helps prevent excessive wear and tear on any single pair. && 6. Spot Treat as Needed: Address any new stains or marks promptly to prevent them from becoming permanent. Use a gentle cleaning solution and a soft cloth to spot treat the affected area, then allow it to air dry. && 7. Be Mindful of Material: Different materials require different care routines. Leather sneakers may benefit from occasional conditioning to keep them soft and supple, while suede sneakers require regular brushing to maintain their texture. Follow the care instructions provided by the manufacturer for the best results. && By following these simple care tips, you can keep your sneakers looking fresh and stylish for years to come. Remember, a little maintenance goes a long way in preserving the appearance and performance of your favorite kicks."
  }
];