export type ArticleDataType = {
  title: string;
  id: string;
  fullText: string;
};

export const BLOG_DATA: ArticleDataType[] = [
  {
    title: "About us",
    id: "124dfq",
    fullText: "In the vibrant tapestry of online fashion, Nysc Shoes emerged as a beacon of style and compassion in the year 2020. What began as a dream soon transformed into a reality, as the founders envisioned a space where footwear wasn't just a necessity but a statement of individuality and global responsibility. Founded in the midst of a challenging year, Nysc Shoes stood resilient, determined to bring a positive impact to the world. In just a short span, the store became a favorite among fashion enthusiasts, growing to boast a community of over a million satisfied customers. The founders of Nysc Shoes, driven by a passion for fashion and a desire to make a difference, set out to redefine the online shopping experience. With a keen eye for trends and an unwavering commitment to quality, they curated a collection that resonated with the diverse tastes of their growing clientele. Beyond fashion, the heart of Nysc Shoes beats with a spirit of philanthropy. Embracing the principle of giving back, the store actively engages in charitable initiatives aimed at making a positive impact on the community and the world at large. From local outreach programs to global partnerships, Nysc Shoes believes in using its success to contribute to a brighter and more compassionate future. The success of Nysc Shoes isn't just measured in numbers; it's reflected in the stories of customers who found the perfect pair, in the joy of giving, and in the positive ripples created by a community united by a love for fashion and a shared vision for a better world. As the brand continues to flourish, it remains committed to its founding principles – offering top-notch footwear, fostering a sense of style and individuality, and making a meaningful difference in the world. Nysc Shoes isn't just a store; it's a movement, a celebration of fashion with a purpose, and a testament to the transformative power of a community that cares. Step into the world of Nysc Shoes, where every purchase is a step towards self-expression, compassion, and a brighter, more stylish tomorrow."
  },
  {
    title: "How to choose the best running shoes?",
    id: "d120da",
    fullText: "Embarking on a running journey is an exhilarating experience, and the right pair of running shoes can make all the difference. Whether you're a seasoned marathoner or a novice hitting the pavement for the first time, selecting the ideal running shoes is crucial for comfort, performance, and injury prevention. Here's your comprehensive guide to finding the perfect running shoes: 1. Understand Your Foot Type: Begin by identifying your foot type. Are you an overpronator, underpronator, or do you have a neutral gait? Knowing this helps determine the level of support and cushioning your feet require. 2. Get to Know Your Arch: Your arch type influences the distribution of impact forces while running. High, normal, or low arches each have specific shoe requirements. Understanding your arch helps in selecting shoes with the right arch support. 3. Assess Your Running Terrain: Consider the surface you'll be running on – be it trails, roads, or a mix of both. Different terrains demand different features in running shoes. Trail shoes offer more traction, while road shoes focus on lightweight construction. 4. Know Your Running Style: Your running style and goals influence the type of shoes you need. If you're a sprinter, you might prefer lightweight and responsive shoes. Long-distance runners may prioritize cushioning and durability. 5. Measure Your Feet Regularly: Believe it or not, your shoe size can change over time. Measure your feet regularly to ensure a proper fit. Feet tend to swell during a run, so consider shopping for shoes in the late afternoon or evening. 6. Comfort is Key: Always prioritize comfort. Your running shoes should feel snug but not tight. Make sure there's enough room in the toe box to prevent black toenails and blisters. Walk around and jog a bit in the store to assess the comfort level. 7. Test the Flexibility: A good pair of running shoes should bend at the ball of the foot but remain sturdy in the arch. This balance ensures proper support and flexibility, contributing to a more natural stride. 8. Consider the Right Cushioning: The level of cushioning depends on your personal preference and the distance you plan to cover. Some runners prefer a plush feel for longer distances, while others may opt for a firmer cushioning for speed. 9. Allow Room for Orthotics: If you use orthotic insoles, ensure the running shoes have enough space to accommodate them comfortably. Some shoes come with removable insoles, providing flexibility for custom orthotics. 10. Seek Professional Advice: Don't hesitate to seek advice from professionals at specialty running stores. They can analyze your gait, foot type, and running style to recommend the most suitable options. Remember, investing time and effort into choosing the right running shoes pays off in the long run – both in terms of comfort and injury prevention. Lace up, hit the pavement, and enjoy every stride on your running journey."
  },
];
